feat(CMD): add new local user store commands to CLI
SSHcom/privx-cli pull request #11
Opened 2021-05-21 05:55 UTC by iljaSL

Added new commands to the CLI to interact with the public PrivX local user store API's.

The following endpoints are covered - > https://privx.docs.ssh.com/reference#get_local-user-store-api-v1-users

2021-05-21 13:26 UTC, cuongssh requested changes
I think the main resources in users.go like api-clients, extenders, webproxies, tags should be moved to first level. We could discuss this more over Slack

2021-05-24 13:35 UTC, iljaSL commented
Separated the commands in different files.
Renamed the commands and cmd functions.
`usersRolesCmd` will be refactored later, when I'm covering the role store endpoints.

2021-06-03 14:49 UTC, cuongssh requested changes

2021-06-03 14:49 UTC, cuongssh commented on cmd/users.go
> +	return err
Line 272-276 does not make much sense. Either return err in all cases or nil explicitly

2021-06-04 14:13 UTC, cuongssh approved these changes

2021-06-04 14:13 UTC, merged