refactor: move local user related cmds to new file, rf existing cmds
SSHcom/privx-cli pull request #29
Opened 2021-08-03 10:19 UTC by iljaSL

Moved exsting local user commands to a new file to keep them separated from the role store related commands.
Refactored the cmds layout.

2021-08-04 10:46 UTC, cuongssh requested changes

2021-08-04 10:46 UTC, cuongssh commented on cmd/apiclients.go
> +	cmd.AddCommand(apiClientCreateCmd())
probably wrong place to add command

2021-08-04 11:13 UTC, iljaSL commented
Moved the misplaced command declarations to the right place.

2021-08-05 05:51 UTC, cuongssh approved these changes

2021-08-05 05:52 UTC, merged