feat: add new authorizer cmds
SSHcom/privx-cli pull request #35
Opened 2021-08-24 07:31 UTC by iljaSL

2021-08-24 12:54 UTC, cuongssh requested changes
The files are OK except webproxy lacks the configuration file donwload. 

It got a bit complicated as extender, web-proxy and carrier are trusted clients that also have data fetched through local-user-store micro-service. The List, Show sub-commands are actually list the CAs instead of showing  or listing the component's data.

I suggest, in addition to the missing conf download, the following:
- Save list and show sub-command for the calls to local-user-store to pull out the component data. Change the current list and show sub-command to list-ca and show-ca. 
- Similarly, revocation-list can be shortened to show-crl 
- webproxy consists of a web-proxy component and a carrier component. If the whole package is addressed by a single command "web-proxy"  then make sure it returns data from both components, or from a specific component if asked. If the whole package is addressed separately by "web-proxy" and "carrier" commands then add carrier.go

2021-08-24 12:54 UTC, cuongssh commented on cmd/principals.go
> +		Short: "Get a signature",
Sign data using principal private key?

2021-08-26 11:11 UTC, iljaSL commented
Restructured trusted client commands into one file -> extender.go
User can now choose with the `type` flag for a specific component.

2021-09-04 08:36 UTC, cuongssh requested changes

2021-09-04 08:36 UTC, cuongssh commented on cmd/extender.go
> +		Use:          "extender",
Based on the usage it seems that the top-most command should be "clients" or "trusted-clients" as it covers extender, web-proxy and carrier now.

2021-09-06 07:25 UTC, iljaSL commented
Renamed the `extender` command to `trusted-clients`, as `clients` was already in use.
Renamed also the file, functions, variables etc. according to the command name change.

2021-09-06 11:16 UTC, cuongssh approved these changes

2021-09-06 11:16 UTC, merged